default-model: bedrock-claude-3-haiku
models:
    bedrock-claude-3-haiku:
        provider: bedrock
        settings:
            region: us-east-1
            model-id: anthropic.claude-3-haiku-20240307-v1:0
        tools:
            - top_song
    bedrock-sonnet-3.5-v1:
        provider: bedrock
        settings:
            region: us-east-1
            model-id: anthropic.claude-3-5-sonnet-20240620-v1:0
    bedrock-titan-premier:
        provider: bedrock
        settings:
            region: us-east-1
            model-id: amazon.titan-text-premier-v1:0
tool-plugins:
    top_song: /Users/lewis/Development/prompt/plugins/top_song.js
