[package]
name = "prompt_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
rquickjs = { workspace = true }
serde_yml = "0.0.12"
serde = { version = "1.0.216", features = ["derive"] }
llrt_modules = { path = "/Users/lewis/Development/llrt/llrt_modules" }